language: node_js

sudo: true

node_js:
  - "node"

before_install:
  - sudo apt-get install libsecret-1-dev
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
    sh -e /etc/init.d/xvfb start;
    sleep 3;
    fi

install:
  - npm install
  - npm run vscode:prepublish



